imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/core/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

